        `spring.application.name=stamps

server.port=${PORT:8080}

#spring.datasource.url=jdbc:postgresql://localhost:5433/stampsdb
#spring.datasource.username=postgres
#spring.datasource.password=Pawan@123

spring.datasource.url=jdbc:postgresql://google/stamps-db?cloudSqlInstance=project-5176d167-2b21-4712-a35:asia-south1:stamps-new-db2&socketFactory=com.google.cloud.sql.postgres.SocketFactory
spring.datasource.username=stamps-new
spring.datasource.password=Pawan@123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true







